def clean_text(content):
  new_list =[]
  for item in content:
    item = item.replace ('topline', 'revenue')
    item = item.replace ('top line', 'revenue')
    item = item.replace ('bottomline', 'net profit')
    item = item.replace ('bottom line', 'net profit')
    item = item.replace ('earning per share', 'EPS')
    item = item.replace ('earnings per share', 'EPS')
    item = item.replace ('earnings per share', 'EPS')
    item = item.replace ('Earning per share', 'EPS')
    item = item.replace ('flat', 'unchanged')
    item = item.replace ('capacity utilisation', 'കപ്പാസിറ്റി വിനിയോഗം')
    item = item.replace ('outlook', 'expectation')
    item = item.replace ('core', 'basic')
    item = item.replace ('YoY', ' over the previous year ')
    item = item.replace ('Order execution', 'ഓർഡർ എക്സിക്യൂഷൻ')
    item = item.replace ('execution', 'implementation')
    item = item.replace ('margins', 'margin')
    item = item.replace ('modest', 'small')
    item = item.replace (' per ', ' for a ')
    item = item.replace ('formulations', 'ഫോറമൂലേഷൻസ് ')
    item = item.replace ('Rs.', 'Rs')
    item = item.replace ('Valuations', 'വാല്യുയേഷൻ')
    item = item.replace ('valuation', 'വാല്യുയേഷൻ')
    item = item.replace ('mix', 'മിക്സ്')
    item = item.replace ('Order pipeline', 'ഓർഡർ പൈപ്പ് ലൈൻ')
    item = item.replace ('order pipeline', 'ഓർഡർ പൈപ്പ് ലൈൻ')
    item = item.replace ('supported by', 'on account of')
    item = item.replace ('muted', 'slow')
    item = item.replace ('key monitorable', 'important aspects to watch')
    item = item.replace ('leisure', 'entertainment')
    item = item.replace ('fleet count', 'number of planes')
    item = item.replace ('risk', 'റിസ്ക്')
    item = item.replace ('realization', 'റിയലയിസെഷന്')
    item = item.replace ('CMP', 'ഇപ്പോഴത്തെ മാർക്കറ്റ് വില')
    item = item.replace ('Buy ', 'ബൈ')
    item = item.replace ('Sell', 'സെല്ല്')
    item = item.replace ('Accumulate', 'ആക്കുമുലേറ്റ്')
    item = item.replace ('Hold', 'ഹോൾഡ്')


    new_list.append(item)

  return new_list